baseURL: "https://tomorrowthief.github.io/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: 钟灵毓秀
pagination: 
    disableAliases: false
    pagerSize: 5
    path: page
theme: hugo-blog
publishDir: docs

languageCode: zh
DefaultContentLanguage: zh
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
hasCJKLanguage: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    zh: 
        languageName: "中文"
        languageAltTitle: "Chinese"
        weight: 1
        menu:
            main:
                - name: 归档
                  url: archives
                  weight: 5
                - name: 查找
                  url: search/
                  weight: 8
                - name: 标签
                  url: tags/
                  weight: 7
                - name: 分类
                  url: categories/
                  weight: 6
                - name: 关于
                  url: about/
                  weight: 9
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    social: true
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "zhongling blog"
    author: zhongling
    # author: ["Me", "You"] # multiple authors

    # disableScrollToTop: true
    defaultTheme: auto
    # disableThemeToggle: true
    # ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    # displayFullLangName: true
    ShowPostNavLinks: true
    # ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: true
    images: ["cover.png"]

    profileMode:
        enabled: false
        title: 钟灵毓秀
        imageUrl: "cover.png"
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: 归档
              url: archives/
            - name: 分类
              url: categories/
            - name: 标签
              url: tags/

    homeInfoParams:
        Title: "钟灵毓秀"
        Content: >
            - 开发者 & 架构师 & 问题终结者

    # editPost:
    #     URL: "https://github.com/tomorrowthief/tomorrowthief.github.io/"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: cover.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
