name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main # Or your source branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # If using Hugo modules

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo --minify --destination docs # Adjust destination if using docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs # Adjust publish_dir if using docs/
          # publish_branch: gh-pages # Uncomment if deploying to a separate gh-pages branch
